/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-07-24 04:29:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\"/>\r\n");
      out.write("<title>장학꿈</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.handong.edu/site/handong/res/css/sub.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.handong.edu/res/js/jquery-1.8.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tdocument.onkeydown = function() { \r\n");
      out.write("\t\tif (event.keyCode == 13) {\r\n");
      out.write("\t\t\tonLogin();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tfunction onLogin()  //login시에 발생하는 이벤트 Post로 \"id_real\" \"pw_real\"를 Login_C.jsp로 넘긴다 \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.frmLogin.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction chkKey(that, divID)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(that.value.length < 1) {\r\n");
      out.write("\t\t\t\t\t$(\"#\"+divID+\" img\").attr(\"src\",\"/WebContent/images/x.png\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#\"+divID+\" img\").attr(\"src\",\"/WebContent/images/v.png\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tinput[type=text], input[type=password] {position:absolute; top:0; left:0; width:80%; height:44px; padding:0 5% 0 15%; font-size:13px; background:none; border:none; line-height:44px;}\r\n");
      out.write("\t\t\t#id-container {position:relative; background:#fff; width:100%; height:42px; border:1px solid #e8e8e9; overflow:hidden;} \r\n");
      out.write("\t\t\t#pw-container {position:relative; background:#fff; width:100%; height: 42px; border:1px solid #e8e8e9; margin-top:20px; overflow:hidden;}\r\n");
      out.write("\t\t\t#icon_id, #icon_pw {position:absolute; top:12px; right:20px;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.w_login {width:100%; max-width:840px; }\r\n");
      out.write("\t\t\t.login {position:relative; width:80%; padding:50px 5% 25px 15%;}\r\n");
      out.write("\t\t\t.login .t12 {margin:10px 5px 30px 0; font-size:12px; font-weight:bold; color:#313131; text-align:right; }\r\n");
      out.write("\t\t\t.login .t12 a {color:#313131; margin-left:20px;}\r\n");
      out.write("\t\t\t.login .login_but {display:block; line-height:64px; color:#fff; font-size:17px; font-weight:bold; text-align:center; background-color:#005DBC; repeat-x 0 0; border-radius:3px;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t@media only screen and (max-width:800px) {\r\n");
      out.write("\t\t\t\t.login {width:90%; padding:50px 5% 25px 5%;}\r\n");
      out.write("\t\t\t\tinput[type=text], input[type=password] {width:75%; padding:0 5% 0 20%;}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"w_login\">\r\n");
      out.write("\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t<form class=\"form\" method = \"POST\" name=\"frmLogin\" action = \"Login_C.jsp\"> \r\n");
      out.write("\t\t\t\t<div id=\"id-container\">\r\n");
      out.write("\t\t\t\t<img src=\"/WebContent/images/id.png\" alt=\"chk\" />\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"id\" id =\"id_real\" style=\"\" value=\"\" title=\"아이디 입력\" placeholder=\"아이디를 입력하세요\" maxlength=\"50\" onkeyup=\"chkKey(this, 'icon_id')\" />\r\n");
      out.write("\t\t\t\t<div id=\"icon_id\"><img src=\"/WebContent/images/x.png\" alt=\"chk\" /></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"pw-container\">\r\n");
      out.write("\t\t\t\t<img src=\"/WebContent/images/password.png\" alt=\"chk\" />\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"pw\" id = \"pw_real\" value=\"\" title=\"비밀번호 입력\" placeholder=\"비밀번호를 입력하세요\" autocomplete=\"off\" onkeyup=\"chkKey(this, 'icon_pw')\" maxlength=\"50\" />\r\n");
      out.write("\t\t\t\t<div id=\"icon_pw\"><img src=\"/WebContent/images/x.png\" alt=\"chk\" /></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"t12\">\r\n");
      out.write("\t\t\t\t<a href=\"\">아이디/비밀번호찾기</a>\r\n");
      out.write("\t\t\t\t<a href=\"\" target=\"_blank\">회원가입</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a class=\"login_but\" href=\"javascript:onLogin();\">Login</a>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
