/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-08-18 11:29:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import com.oreilly.servlet.MultipartRequest;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import dao.ScholarDAO;
import dto.ScholarVO;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class manager_005fScholarInfo_005fWrite_005fC_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("manager_ScholarInfo_Write_C.jsp 페이징 입니다. \r\n");
      out.write("\r\n");

ScholarVO newSVO = new ScholarVO();

String in_scholarname="";
String in_foundationname="";
String in_scholarmoney="";
String in_gpa="";
String in_studentstatus="";
String in_schoolname="";
String in_major="";
String in_area="";
String in_startday=null;
String in_endday=null;
String in_dday="";
String in_url="";
String in_link="";
String in_imagename="";
String in_imageurl="";
String in_filename="";
String in_fileurl="";
String in_etc="";
int in_view=1;
int in_manager_check=1;							//직접 입력했으니 1


request.setCharacterEncoding("UTF-8");

String savePath = "attachedFiles";
int uploadFileSizeLimit = 10* 1024 * 1024;
String encType = "UTF-8";

ServletContext context = getServletContext();
String uploadFilePath = context.getRealPath(savePath);

System.out.println("실제 저장 경로 : "+ uploadFilePath);                        //to save files = get saving path 


MultipartRequest multi = new MultipartRequest(request, uploadFilePath, uploadFileSizeLimit, encType, new DefaultFileRenamePolicy());


String fileName = multi.getFilesystemName("file");
if(fileName==null){
	System.out.println("file don't exist");
}else{
	System.out.println("file exist");
}
System.out.println(fileName);



if(multi.getParameter("scholarname")==null){
	System.out.println("writec null");
}

if(multi.getParameter("scholarname")==" "){
	System.out.println("writec empty");
}

in_scholarname = multi.getParameter("scholarname");
in_foundationname = multi.getParameter("foundationname");
in_scholarmoney = multi.getParameter("scholarmoney");
in_gpa = multi.getParameter("gpa");
in_studentstatus = multi.getParameter("studentstatus");
in_schoolname = multi.getParameter("schoolname");
in_major = multi.getParameter("major");
in_area = multi.getParameter("area");
in_startday = multi.getParameter("startday");
in_endday = multi.getParameter("endday");

String match = "[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]";


System.out.println("in_startday 의값은 "+in_startday);

System.out.println("in_scholarname :"+in_scholarname);
if(in_scholarname.equals("")){
	in_scholarname = "정보 없음";
	
}
if(in_foundationname.equals("")){
	in_foundationname = "정보 없음";
	
}
if(in_scholarmoney.equals("")){
	in_scholarmoney = "정보 없음";
	
}
if(in_gpa.equals("")){
	in_gpa = "정보 없음";
	
}
if(in_studentstatus.equals("")){
	in_studentstatus = "정보 없음";
	
}
if(in_schoolname.equals("")){
	in_schoolname = "정보 없음";
	
}
if(in_major.equals("")){
	in_major = "정보 없음";
	
}
if(in_area.equals("")){
	in_area = "정보 없음";
	
}
if(in_startday.equals("")){
	in_startday = "정보 없음";
	
}
if(in_endday.equals("")){
	in_endday = "정보 없음";
	
}

if(in_startday.matches(match)){
	System.out.println("startday가 형식에 맞음");
	String year = in_startday.substring(0,4);
	String month = in_startday.substring(4,6);
	String day = in_startday.substring(6,8);
	in_startday = year+"-"+month+"-"+day;
}else{
	in_startday = multi.getParameter("startday");
}

if(in_endday.matches(match)){
	System.out.println("endday가 형식에 맞음");
	String year = in_endday.substring(0,4);
	String month = in_endday.substring(4,6);
	String day = in_endday.substring(6,8);
	in_endday = year+"-"+ month +"-"+ day;
	
	int endday_year = Integer.parseInt(in_endday.substring(0,4)); // calculate DDAY ==================
	int endday_month = Integer.parseInt(in_endday.substring(5,7));
	int endday_day = Integer.parseInt(in_endday.substring(8,10));
	Calendar cal = Calendar.getInstance();
	long now_day = cal.getTimeInMillis();
	cal.set(endday_year, endday_month-1, endday_day);
	long event_day = cal.getTimeInMillis();
	long d_day = (event_day - now_day)/(60*60*24*1000);
	
	in_dday = String.valueOf((int)d_day); 							//in_dday -> save like "5"

}else{
	in_startday = multi.getParameter("startday");
	
}






in_url = multi.getParameter("url");
in_link = multi.getParameter("link");
in_filename = fileName;
in_fileurl = uploadFilePath+"/"+fileName;
in_etc = multi.getParameter("etc");



/* in_etc=in_etc.replaceAll("\r\n","<BR>");
System.out.println("최종 in_etc"+in_etc);
 */


newSVO.setScholarname(in_scholarname);
newSVO.setFoundationname(in_foundationname);
newSVO.setScholarmoney(in_scholarmoney);
newSVO.setGpa(in_gpa);
newSVO.setStudentstatus(in_studentstatus);
newSVO.setSchoolname(in_schoolname);
newSVO.setMajor(in_major);
newSVO.setArea(in_area);
newSVO.setStartday(in_startday);
newSVO.setEndday(in_endday);
newSVO.setDday(in_dday);
newSVO.setUrl(in_url);
newSVO.setLink(in_link);
newSVO.setFilename(in_filename);
newSVO.setFileurl(in_fileurl);
newSVO.setEtc(in_etc);
newSVO.setManager_check(1);


ScholarDAO sdao = ScholarDAO.getInstance();
sdao.scholarInfoAdd(newSVO);



/* response.sendRedirect("manager_mScholarship_AllList.jsp"); */



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
