/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-08-18 10:38:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manager_005fScholarInfo_005fWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<style type =\"text/css\">\r\n");
      out.write("div.wrapper {\r\n");
      out.write("border : 10px solid #005DBC;\r\n");
      out.write("width : 90%;\r\n");
      out.write("height : 2000px;\r\n");
      out.write("padding : 10px;\r\n");
      out.write("align : center;\r\n");
      out.write("font-family : Arial, Vendana, sans-serif;\r\n");
      out.write("background-color : #fdf5e6;\r\n");
      out.write("margin : 10px auto 10px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.wrapper div {\r\n");
      out.write("background-color : #00FF40;\r\n");
      out.write("margin : 10px auto 10px auto;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("background-color : #F4FA58;\r\n");
      out.write("\r\n");
      out.write("margin : 10px auto 10px auto;\r\n");
      out.write("padding : 10px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "manager_Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class =\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("<div><h2>장학금 재단 정보 입력 (관리자 페이지)</h2></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form method = post action = \"manager_ScholarInfo_Write_C.jsp\" name = \"Write\" ENCTYPE=\"multipart/form-data\">\r\n");
      out.write("<table name = \"infotable\" >\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td >scholarname 입력 (스트링)-------</td><td><input type = text size = 120 placeholder = \"장학금 이름 입력하세요\" name = \"scholarname\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>foundationname 입력(스트링)-------</td><td><input type = text  size = 120 placeholder = \"장학 재단 명을 입력하세요\" name = \"foundationname\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>scholarmoney 입력(스트링)------</td><td><input type = text size = 120 placeholder = \"장학 금액을 입력하세요\" name = \"scholarmoney\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>gpa 입력(스트링)------</td><td><input type = text size = 120 placeholder = \"학점 기준을 입력하세요\" name = \"gpa\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>studentstatus 입력(스트링)------</td><td><input type = text size = 120 placeholder = \"소득 분위 기준을 입력하세요\" name = \"studentstatus\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>schoolname 입력(스트링)------ </td><td><input type = text size = 120 placeholder = \"장학금 대상 학교를 입력하세요\" name =\"schoolname\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>major 입력(스트링)------------</td><td><input type = text size = 120 placeholder = \"전공을 입력하세요 \" name =\"major\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>area 입력(스트링)------------</td><td><input type = text size = 120 placeholder = \"장학금 지역을 입력하세요\" name =\"area\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>startday 입력(20120405 혹은 글자도 가능)</td><td><input type = text size = 120 placeholder = \"시작날자를 입력하세요(20150503 또는 문자 가능)\" name = \"startday\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>endday 입력(20120405 혹은 문자도 가능)</td><td><input type = text size = 120 placeholder = \"마감날자를 입력하세요(20150503 또는 문자 가능)\" name = \"endday\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>url (해당 정보를 얻어온 곳)------ </td><td><input type = text size = 120 placeholder = \"해당 정보를 얻어온 url을 입력하세요 \" name = \"url\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>link 입력(정보가 있는 곳)------</td><td><input type = text size = 120 placeholder = \"장학 재단의 link를 입력하세요 \" name =\"link\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>첨부파일 추가 1------</td><td><input type = FILE size = 120 name =\"file\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>etc 입력(스트링)</td><td><textarea rows=\"70\" cols=\"125\" name=\"etc\"></textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td> ===================================</td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<input type = \"submit\" value =\"새 장학금 등록 완료\">\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
