/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-08-20 03:10:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager_005fboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manager_005fHeader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>장학꿈</title>\n");
String Ver = "/WebContent/";
  String eclipseVer = "../";
  String UploadVer = "/WebContent/";
      out.write("\n");
      out.write("  \n");
      out.write("<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\n");
      out.write("<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\n");
      out.write("<meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(Ver );
      out.write("css/common.css\"> <!-- 폰트 -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(Ver );
      out.write("css/layout.css\" /> <!-- Layout -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(Ver );
      out.write("css/header.css\">\n");
      out.write("\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\" /> <!— 메뉴바 X표시 —>\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script> <!— 메뉴바 반응형 —>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(Ver );
      out.write("js/mobile.js\"></script> <!-- 메뉴바 반응형 -->\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(Ver );
      out.write("js/scroll.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"wrapper\" class = \"service SET_B\" style=\"text-align:center\">\n");
      out.write("<header border =\"1\" id = \"header\" class = \"SET_B\">\t\n");
      out.write("\t<!-- 메인 헤더 -->\t\t\n");
      out.write("\t\t<div id = \"mainHeader\" class = \"skin_background\">\t\t\t\n");
      out.write("\t\t<ul class = \"headerList\">\n");
      out.write("\t\t\t<li class = \"headerLeft\">\n");
      out.write("\t\t\t\t<span id = \"menu_button\" class = \"top-nav\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(Ver );
      out.write("images/menu.png\">\n");
      out.write("\t\t\t\t</span>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li class = \"headerCenter\">\n");
      out.write("\t\t\t\t <span>장학꿈</span>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li class = \"headerRight\">\n");
      out.write("\t\t\t\t<span id = \"search_button\" class = \"top-nav\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(Ver );
      out.write("images/search.png\">\n");
      out.write("\t\t\t\t</span>\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 메인 헤더 -->\t\t\t\t\n");
      out.write("\n");
      out.write("\t<!-- 왼쪽 메뉴 -->\n");
      out.write("\t<aside id=\"mainMenuContainer\" class = \"border-box\">\t\t\t\t\n");
      out.write("\t\t<nav class=\"mainMenuContainer-inner\">\t\t\t\t\t\t\n");
      out.write("\t\t\t<section class=\"menu-search\">\n");
      out.write("\t\t\t\t<h2 class = \"hiddenText\">검색</h2>\n");
      out.write("\t\t\t\t<form name = \"searchForm\" method = \"post\" action = \"manager_mTop_SearchList.jsp\" id = \"mainSearchForm\">\n");
      out.write("\t\t\t\t\t<input type = \"hidden\" name = \"sc_area\" value = \"A\">\n");
      out.write("\t\t\t\t\t<input type=\"search\" name=\"sc_word\" placeholder=\"검색어를 입력하세요!\" class=\"keyword border-box menu-sch-input ft-fa2\" >\n");
      out.write("\t\t\t\t\t<button class = \"searchButton\">검색</button>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t<a id=\"menuClose\"><i class=\"fa fa-times fa-2x\"></i></a>\n");
      out.write("\t\t\t</section>\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<section class=\"menu border-box\" style=\"text-align:center\">\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<h2 class=\"ft-fa1\">로그인</h2>\t\t\t\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-chevron-right\"></i>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<section class=\"menu border-box\" style=\"text-align:center\">\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<h2 class=\"ft-fa1\">메인화면</h2>\t\t\t\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-chevron-right\"></i>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<section class=\"menu border-box\" style=\"text-align:center\">\n");
      out.write("\t\t\t\t<a  href=\"#\">\n");
      out.write("\t\t\t\t\t<h2 class=\"ft-fa1\">장학꿈소개</h2>\t\t\t\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-chevron-right\"></i>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<section class=\"menu border-box\" style=\"text-align:center\">\n");
      out.write("\t\t\t\t<a  href=\"#\">\n");
      out.write("\t\t\t\t\t<h2 class=\"ft-fa1\">공지사항</h2>\t\t\t\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-chevron-right\"></i>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<ul id = \"news-category-list\">\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">신규장학금</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"manager_mTop_popularList.jsp\">인기장학금</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"manager_mScholarship_AllList.jsp\">전체장학금</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"manager_mScholarship_ingList.jsp\">진행장학금</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"manager_mScholarship_endedList.jsp\">마감장학금</a></li>\t\t\n");
      out.write("\t\t\t</ul>\t\t\t\t\t\t\n");
      out.write("\t\t</nav>\n");
      out.write("\t</aside>\t\n");
      out.write("\t<!-- 왼쪽 메뉴 -->\n");
      out.write("\n");
      out.write("\t<!-- 상단 돋보기 검색바 -->\n");
      out.write("\t<div id = \"subSearchForm\" class=\"skin_background\">\t\t\t\t\n");
      out.write("\t\t<form name = \"searchForm\" class = \"searchForm\" method = \"post\" action = \"manager_mTop_SearchList.jsp\">\n");
      out.write("\t\t\t<input type = \"hidden\" name = \"sc_area\" value = \"A\">\n");
      out.write("\t\t\t<input type = \"text\" name = \"sc_word\" class = \"keyword\">\n");
      out.write("\t\t\t<button  class = \"button_3 searchButton\">검색</button>\t\t\n");
      out.write("\t\t</form>\t\t\t\t\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 상단 돋보기 검색 검색바 -->\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"wrap\">\n");
      out.write("    <nav id=\"topMenu\">\n");
      out.write("    <ul id=\"scroller\">\n");
      out.write("\t\t<li><a class=\"top-menu0 on\" href=\"\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">신규장학금</a></li>\n");
      out.write("\t\t<li><a class=\"top-menu1\" href=\"manager_mTop_popularList.jsp\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">인기장학금</a></li>\n");
      out.write("\t\t<li><a class=\"top-menu2\" href=\"manager_mScholarship_AllList.jsp\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">전체장학금</a></li>\n");
      out.write("\t\t<li><a class=\"top-menu3\" href=\"manager_mScholarship_ingList.jsp\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">진행장학금</a></li>\n");
      out.write("\t\t<li><a class=\"top-menu4\" href=\"manager_mScholarship_endedList.jsp\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">마감장학금</a></li>\n");
      out.write("\t\t<li><a class=\"top-menu5\" href=\"manager_ScholarInfo_Write.jsp\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">★장학꿈 정보 직접 입력</a></li>\n");
      out.write("\t\t<li><a class=\"top-menu6\" href=\"manager_CrawleringButton.jsp\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">★장학꿈 정보 크롤링 입력</a></li>\n");
      out.write("\t\t\t<li><a class=\"top-menu6\" href=\"manager_mScholarship_CrawleringCheckList.jsp\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">★크롤링 정보확인</a></li>\n");
      out.write("\t\t<li><a class=\"top-menu6\" href=\"\" data-cclick=\"MOBILE_,SCROLLER,TODAYRECOMM,0\">★공지사항 입력 </a></li>\n");
      out.write("\t\n");
      out.write("    </ul>\n");
      out.write("    <span id=\"scroller-left\" class=\"scroller-arr-left\" data-cclick=\"MOBILE_,SCROLLER,LEFT,0\"></span>\n");
      out.write("    <span id=\"scroller-right\" class=\"scroller-arr-right active\" data-cclick=\"MOBILE_,SCROLLER,RIGHT,0\"></span>\n");
      out.write("</nav>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(window).load(function(){\n");
      out.write("\tmobile.initDefaultEvent('http://scholarshipcenter.co.kr','mobile');\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    \"use strict\";\n");
      out.write("    var iscroll;\n");
      out.write("    var actArrw = function() {\n");
      out.write("        $('#scroller-left,#scroller-right').addClass('active');\n");
      out.write("        0 === iscroll.x ? $(\"#scroller-left\").removeClass(\"active\")\n");
      out.write("                : iscroll.x === iscroll.maxScrollX &&\n");
      out.write("                $(\"#scroller-right\").removeClass(\"active\");\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    var selectedTopmenu = \"top-menu0\";\n");
      out.write("\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        $('#main-banner').click(function() {\n");
      out.write("            if(!($(this).attr(\"href\"))){\n");
      out.write("                coupangApp.go('', 'homeBanner');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        /*\n");
      out.write("         *\tGNB 선택 후 선택한 메뉴가 스크롤이 필요한 경우\n");
      out.write("         *\tTODO: scrolltopage를 이용하게 되면 페이지 로딩 시 강제로 스크롤을 하게 되서 애니메이션 효과 발생\n");
      out.write("         *\t그대로 두는지 아예 로딩 시 iscroll객체 생성 시 기본값을 주는지 선\n");
      out.write("         */\n");
      out.write("\n");
      out.write("        var _menuIndex = $(\"#scroller li a\").index($(\".\" + selectedTopmenu));\n");
      out.write("        iscroll.goToPage(_menuIndex, 0, 0);\n");
      out.write("        actArrw();\n");
      out.write("\n");
      out.write("        /* Flicking */\n");
      out.write("        if($('#todayshot-section').hasClass('isFlicking')){\n");
      out.write("            var panelTime;\n");
      out.write("\n");
      out.write("            $(\"#todayshotList\").touchSlider({\n");
      out.write("                speed : 400,\n");
      out.write("                flexible : true,\n");
      out.write("                rolling : true,\n");
      out.write("                page : 1,\n");
      out.write("                initComplete : function (e) {\n");
      out.write("                    $(\"#todayshotIndicator\").html(\"\");\n");
      out.write("                    $(\"#todayshotList ul li\").each(function (i, el) {\n");
      out.write("                        if((i+1) % e._view == 0) {\n");
      out.write("                            $(\"#todayshotIndicator\").append('<li></li>');\n");
      out.write("                        }\n");
      out.write("                    });\n");
      out.write("                    $('#todayshotList img').load(function(){$(window).trigger('resize')});\n");
      out.write("                },\n");
      out.write("                counter : function (e) {\n");
      out.write("                    $(\"#todayshotIndicator li\").removeClass(\"on\").eq(e.current-1).addClass(\"on\");\n");
      out.write("                    clearInterval(panelTime);\n");
      out.write("                    panelTime = setInterval(function(){$(\"#todayshotList\").get(0).animate(-1,true)},3000);\n");
      out.write("                },\n");
      out.write("                custom : function (){\n");
      out.write("                    clearInterval(panelTime);\n");
      out.write("                },\n");
      out.write("                onTouchEnd : function() {\n");
      out.write("\t\t\t\t\t// todayshotList_show_cnt++;\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            panelTime = setInterval(function(){$(\"#todayshotList\").get(0).animate(-1,true)},5000);\n");
      out.write("\n");
      out.write("            $(window).bind({\n");
      out.write("                resize : function() {\n");
      out.write("                    $(\"#todayshotList\").height($(\"#todayshotList img\").height());\n");
      out.write("                },\n");
      out.write("                load : function() {\n");
      out.write("                    $(\"#todayshotList\").height($(\"#todayshotList img\").height());\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        };\n");
      out.write("        /* Flicking */\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    /* v3. script */\n");
      out.write("    if($('#topMenu').size() > 0 && $('#scroller').size() > 0){\n");
      out.write("        $('#scroller').width(document.getElementById('scroller').scrollWidth + 52);\n");
      out.write("\n");
      out.write("        var scrollOption = {\n");
      out.write("            snap : 'li',\n");
      out.write("            scrollX : true,\n");
      out.write("            scrollY : false,\n");
      out.write("            eventPassthrough : true\n");
      out.write("        };\n");
      out.write("        if(navigator.userAgent.match(/iphone/i) ||\n");
      out.write("                navigator.userAgent.match(/ipad/i)){\n");
      out.write("            scrollOption.useTransform = false;\n");
      out.write("        }\n");
      out.write("        iscroll = new IScroll('#topMenu', scrollOption);\n");
      out.write("        iscroll.on('scrollEnd', actArrw);\n");
      out.write("        $('#scroller-left,#scroller-right').click(function() {\n");
      out.write("            $(this).hasClass(\"scroller-arr-left\") ? iscroll.prev() : iscroll.next();\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
