/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-08-19 06:28:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager_005fboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manager_005fCrawleringButton_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div.wrapper {\r\n");
      out.write("\tborder: 10px solid #005DBC;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\theight: 90%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmin-height: 100px;\r\n");
      out.write("\talign: center;\r\n");
      out.write("\tfont-family: Arial, Vendana, sans-serif;\r\n");
      out.write("\tbackground-color: #fdf5e6;\r\n");
      out.write("\tmargin: 10px auto 10px auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\tfunction crawlering() {\r\n");
      out.write("\t\tvar gsWin = window\r\n");
      out.write("\t\t\t\t.open('about:blank', 'crawlerviewer',\r\n");
      out.write("\t\t\t\t\t\t'scrollbars=yes,toolbar=yes,resizable=yes,width=600,height=1000');\r\n");
      out.write("\t\tvar frm = document.select_box_form;\r\n");
      out.write("\t\tfrm.action = 'manager_CrawleringButton_C.jsp';\r\n");
      out.write("\t\tfrm.target = \"crawlerviewer\";\r\n");
      out.write("\t\tfrm.method = \"post\";\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "manager_Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div>이것은 실험 파일 크롤링할 사이트를 선택하시고 확인을 누르세요</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"selector_box\">\r\n");
      out.write("\t\t\t<form name=\"select_box_form\" action=\"manager_CrawleringButton_C.jsp\">\r\n");
      out.write("\t\t\t\t<select id=\"crawler_select\" name=\"crawler_select\">\r\n");
      out.write("\t\t\t\t\t<option value=\"jangHakDoSa\">장학도사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"dreamSpon\">드림스폰</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_SeoulNational\">서울대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_YonSei\">연세대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_Korea\">고려대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_SoGang\">서강대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_SungKyunKwan\">성균관대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_HanYang\">한양대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_Chung-Ang\">중앙대학교(실행불가)</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_KyungHee\">경희대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_Hurfs\">한국외국어대학교대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_SeoulCity\">서울시립대학교</option>\r\n");
      out.write(" \t\t\t\t\t<option value=\"school_KonKuk\">건국대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_DongGuk\">동국대학교</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"school_HongIk\">홍익대학교(실행불가)</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"etc\">기타</option>\r\n");
      out.write("\t\t\t\t</select> <input type=\"button\" value=\"크롤링 시작\" onclick=\"crawlering()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
