/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-08-20 03:06:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager_005fboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.ScholarDAO;
import dto.ScholarVO;
import java.util.Calendar;

public final class manager_005fmContent_005fdetailInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
String Ver = "/WebContent/";
  String eclipseVer = "../";
  String UploadVer = "/WebContent/";
      out.write("\n");
      out.write("  \n");
      out.write("  \n");
      out.write("<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\n");
      out.write("<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\n");
      out.write("<meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\" />\n");
      out.write("<title>장학꿈</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(Ver);
      out.write("/css/content.css\">\n");
      out.write("\n");
      out.write("<script language=\"javascript\">\n");
      out.write("\n");
      out.write("function del(rcdno)\n");
      out.write("{\n");
      out.write("var del\n");
      out.write("\n");
      out.write("del=confirm(\"정말 삭제하시겠습니까?\")\n");
      out.write("\n");
      out.write("if (del == true)\n");
      out.write("{\n");
      out.write("\n");
      out.write("location.replace(\"manager_mContent_detailInfo_Delete.jsp?rcdno=\"+rcdno)\n");
      out.write("}\n");
      out.write("else\n");
      out.write("{\n");
      out.write("alert(\"취소되었습니다!\")\n");
      out.write("\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function crawler_check(rcdno)\n");
      out.write("{\n");
      out.write("var check\n");
      out.write("\n");
      out.write("check=confirm(\"DB에 정보가 제대로 입력되었습니까?\")\n");
      out.write("\n");
      out.write("if (check == true)\n");
      out.write("{\n");
      out.write("\n");
      out.write("location.replace(\"manager_mContent_CrawlerCheck_C.jsp?rcdno=\"+rcdno)\n");
      out.write("}\n");
      out.write("else\n");
      out.write("{\n");
      out.write("alert(\"취소되었습니다!\")\n");
      out.write("\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function status_change(rcdno)\n");
      out.write("{\n");
      out.write("var check\n");
      out.write("\n");
      out.write("check=confirm(\"장학금 기간이 마감되었습니까?\")\n");
      out.write("\n");
      out.write("if (check == true)\n");
      out.write("{\n");
      out.write("\n");
      out.write("location.replace(\"manager_mContent_StatusChange_C.jsp?rcdno=\"+rcdno)\n");
      out.write("}\n");
      out.write("else\n");
      out.write("{\n");
      out.write("alert(\"취소되었습니다!\")\n");
      out.write("\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");

String rcdno = request.getParameter("rcdno"); 						//get request's "rcdno"

ScholarDAO sdao = ScholarDAO.getInstance();
sdao.updateScholarInfoView(rcdno);
ScholarVO detailSVO = sdao.selectDetailInfo(rcdno);


      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "manager_Header.jsp", out, false);
      out.write("\n");
      out.write("<body id=\"bListGi\" class=\"mGib showLayer\">\n");
      out.write("<div id=\"wrap\">\n");
      out.write("\t<section id=\"scC\" class=\"sc scCt scWing\">\n");
      out.write("\t<div class=\"content mGib\">\n");
      out.write("\t\t<div class=\"companyBox\" style=\"background: rgb(128, 128, 128);\">\n");
      out.write("\t\t\t<div class=\"cLogo\">\n");
      out.write("\t\t\t\t<p class=\"cName XXX_19807647\">");
      out.print(detailSVO.getFoundationname() );
      out.write("</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"cInfo wordBreak\">");
      out.print(detailSVO.getScholarname() );
      out.write("</div>\n");
      out.write("\t\t\t<div class=\"wrapFunction\">\n");
      out.write("\t\t\t\t<button class=\"btnFavorite \" id=\"btnFavorite\"><i class=\"fa fa-heart-o fa-lg\"></i> <strong>");
      out.print(detailSVO.getView() );
      out.write("</strong></button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t<section class=\"mGibCt\">\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<h2 class=\"hdGib\">신청기간</h2>\n");
      out.write("\t\t\t\t<p class=\"applyDate applyDate_GIB\">\n");
      out.write("\t\n");
//============================================Startday & Endday & DDay calculate start ================================================			
String checkString = "[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]";
String endday = "";

if(detailSVO.getEndday().matches(checkString)){                  //if endday pattern matches like " 2015-08-15" ->  dday can be calculated
	System.out.println("end day matches our pattern : "+detailSVO.getEndday());


	int endday_year = Integer.parseInt(detailSVO.getEndday().substring(0,4)); // calculate DDAY ==================
	int endday_month = Integer.parseInt(detailSVO.getEndday().substring(5,7));
	int endday_day = Integer.parseInt(detailSVO.getEndday().substring(8,10));
	Calendar cal = Calendar.getInstance();
	long now_day = cal.getTimeInMillis();
	cal.set(endday_year, endday_month-1, endday_day);
	long event_day = cal.getTimeInMillis();
	long d_day = (event_day - now_day)/(60*60*24*1000);
	
	String dday = String.valueOf((int)d_day); 								//in_dday -> save like "5"
			
      out.write("<span class=\"deadline\">\n");
      out.write("\t\t\tD-Day<strong> ");
      out.print(dday);
      out.write("</strong>\n");
      out.write("\t\t\t</span>\n");
      out.write("\t\t\t<span class=\"period devFontFixed\"><span class=\"btContest btStart\">시작</span>");
      out.print(detailSVO.getStartday() );
      out.write("</br><span class=\"btContest btStart\">마감</span>");
      out.print(detailSVO.getEndday() );
      out.write("</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t");


}else {				//if can't calculate DDAY ========================
			
      out.write("\t\t\t<span class=\"deadline\">\n");
      out.write("\t\t\t\t\t<strong>");
      out.print(detailSVO.getEndday() );
      out.write("</strong>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t<span class=\"period devFontFixed\"><span class=\"btContest btStart\">시작</span>정보 없음 </br><span class=\"btContest btStart\">마감</span> 정보 없음 </span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t");
										
	
}


	
      out.write("\n");
      out.write("\t\n");
      out.write("<!-- ----------------------------------------------ㄴStartday & Endday &  DDay calculate ENDED---------------------------------------------------- -->\n");
      out.write("\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<h2 class=\"hdGib\">장학정보</h2>\n");
      out.write("\t\t\t\t<dl class=\"scCnt\">\n");
      out.write("\t\t\t\t\t<dt>성적구분</dt>\n");
      out.write("\t\t\t\t\t<dd>");
      out.print(detailSVO.getGpa() );
      out.write("</dd>\n");
      out.write("\t\t\t\t\t<dt>소득구분</dt>\n");
      out.write("\t\t\t\t\t<dd>");
      out.print(detailSVO.getStudentstatus() );
      out.write("</dd>\n");
      out.write("\t\t\t\t\t<dt>장학금액</dt>\n");
      out.write("\t\t\t\t\t<dd>");
      out.print(detailSVO.getScholarmoney() );
      out.write("</dd>\n");
      out.write("\t\t\t\t\t<dt>특정대학</dt>\n");
      out.write("\t\t\t\t\t<dd>");
      out.print(detailSVO.getSchoolname() );
      out.write("</dd>\n");
      out.write("\t\t\t\t\t<dt>전공구분</dt>\n");
      out.write("\t\t\t\t\t<dd>");
      out.print(detailSVO.getMajor() );
      out.write("</dd>\n");
      out.write("\t\t\t\t\t<dt>거주지역</dt>\n");
      out.write("\t\t\t\t\t<dd>");
      out.print(detailSVO.getArea() );
      out.write("</dd>\n");
      out.write("\t\t\t\t\t<dt>홈페이지</dt>\n");
      out.write("\t\t\t\t\t<dd><a href=\"");
      out.print(detailSVO.getLink());
      out.write("\" target=\"_blank\" >");
      out.print(detailSVO.getLink());
      out.write("</a></dd>\n");
      out.write("\t\t\t\t\t<dt>출처</dt>\n");
      out.write("\t\t\t\t\t<dd><a href=\"");
      out.print(detailSVO.getUrl());
      out.write("\" target=\"_blank\" >");
      out.print(detailSVO.getUrl());
      out.write("</a></dd>\n");
      out.write("\t\t\t\t\t<dt>첨부파일</dt>\n");
      out.write("\t\t\t\t\t<dd><a href=\"");
      out.print(detailSVO.getFileurl());
      out.write("\" target=\"_blank\" >");
      out.print(detailSVO.getFileurl());
      out.write("</a></dd>\n");
      out.write("\t\t\t\t</dl>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<h2 class=\"hdGib\">상세정보</h2>\n");
      out.write("\t\t\t\t");
 																		// etc 부분의 개행 <br>을 추가 해준다. 
				String etcBefore = detailSVO.getEtc();
				String etcFinal = etcBefore.replaceAll("\n\r","<br><br>");
      out.write("\n");
      out.write("\t\t\t\t<p>");
      out.print(etcFinal );
      out.write("</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<p><a href=\"javascript:history.go(-1)\" class=\"bt bt2 btC3 f\"><span>뒤로가기<span class=\"icnGib icn_arr2 icnRt\"></span></span></a></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<p><a href=\"javascript:crawler_check('");
      out.print(rcdno );
      out.write("')\" class=\"bt bt2 btC3 f\"><span>정보 확인<span class=\"icnGib icn_arr2 icnRt\"></span></span></a></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<p><a href=\"javascript:status_change('");
      out.print(rcdno );
      out.write("')\" class=\"bt bt2 btC3 f\"><span>마감 장학금으로 변경<span class=\"icnGib icn_arr2 icnRt\"></span></span></a></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<p><a href=\"manager_mContent_detailInfo_Modify.jsp?rcdno=");
      out.print(rcdno );
      out.write("\" class=\"bt bt2 btC3 f\"><span>수정하기<span class=\"icnGib icn_arr2 icnRt\"></span></span></a></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"sc\">\n");
      out.write("\t\t\t\t<p><a href=\"javascript:del('");
      out.print(rcdno );
      out.write("')\" class=\"bt bt2 btC3 f\"><span>삭제하기<span class=\"icnGib icn_arr2 icnRt\"></span></span></a></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</section>\n");
      out.write("\t</div>\n");
      out.write("\t</section>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
