/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-09-30 14:18:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.safehouse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005fmap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    <!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("        <html>\r\n");
      out.write("        <head>\r\n");
      out.write("        <meta charset =\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </head>\r\n");
      out.write("        <body>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"map\" style=\"width:100%;height:350px;\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ÁöµµÅ¸ÀÔ ÄÁÆ®·Ñ div ÀÔ´Ï´Ù -->\r\n");
      out.write("        <div class=\"custom_typecontrol radius_border\">\r\n");
      out.write("        <span id=\"btnRoadmap\" class=\"selected_btn\" onclick=\"setMapType('roadmap')\">Áöµµ</span>\r\n");
      out.write("        <span id=\"btnSkyview\" class=\"btn\" onclick=\"setMapType('skyview')\">½ºÄ«ÀÌºä</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"//apis.daum.net/maps/maps3.js?apikey=55f963883949bc753ea770926b224e1a\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var mapContainer = document.getElementById('map'), // Áöµµ¸¦ Ç¥½ÃÇÒ div\r\n");
      out.write("        mapOption = {\r\n");
      out.write("        center: new daum.maps.LatLng(36.0114745, 129.3659577), // ÁöµµÀÇ Áß½ÉÁÂÇ¥\r\n");
      out.write("        level: 3 // ÁöµµÀÇ È®´ë ·¹º§\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var map = new daum.maps.Map(mapContainer, mapOption); // Áöµµ¸¦ »ý¼ºÇÕ´Ï´Ù\r\n");
      out.write("\r\n");
      out.write("        // ¸¶Ä¿°¡ Ç¥½ÃµÉ À§Ä¡ÀÔ´Ï´Ù\r\n");
      out.write("        var markerPosition  = new daum.maps.LatLng(36.0114745,129.3659577);\r\n");
      out.write("\r\n");
      out.write("        // ¸¶Ä¿¸¦ »ý¼ºÇÕ´Ï´Ù\r\n");
      out.write("        var marker = new daum.maps.Marker({\r\n");
      out.write("        position: markerPosition\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // ¸¶Ä¿°¡ Áöµµ À§¿¡ Ç¥½ÃµÇµµ·Ï ¼³Á¤ÇÕ´Ï´Ù\r\n");
      out.write("        marker.setMap(map);\r\n");
      out.write("\r\n");
      out.write("        // ¾Æ·¡ ÄÚµå´Â Áöµµ À§ÀÇ ¸¶Ä¿¸¦ Á¦°ÅÇÏ´Â ÄÚµåÀÔ´Ï´Ù\r\n");
      out.write("        // marker.setMap(null);\r\n");
      out.write("\r\n");
      out.write("        // ÀÏ¹Ý Áöµµ¿Í ½ºÄ«ÀÌºä·Î Áöµµ Å¸ÀÔÀ» ÀüÈ¯ÇÒ ¼ö ÀÖ´Â ÁöµµÅ¸ÀÔ ÄÁÆ®·ÑÀ» »ý¼ºÇÕ´Ï´Ù\r\n");
      out.write("        var mapTypeControl = new daum.maps.MapTypeControl();\r\n");
      out.write("\r\n");
      out.write("        // Áöµµ¿¡ ÄÁÆ®·ÑÀ» Ãß°¡ÇØ¾ß ÁöµµÀ§¿¡ Ç¥½ÃµË´Ï´Ù\r\n");
      out.write("        // daum.maps.ControlPositionÀº ÄÁÆ®·ÑÀÌ Ç¥½ÃµÉ À§Ä¡¸¦ Á¤ÀÇÇÏ´Âµ¥ TOPRIGHT´Â ¿À¸¥ÂÊ À§¸¦ ÀÇ¹ÌÇÕ´Ï´Ù\r\n");
      out.write("        map.addControl(mapTypeControl, daum.maps.ControlPosition.TOPRIGHT);\r\n");
      out.write("\r\n");
      out.write("        // Áöµµ È®´ë Ãà¼Ò¸¦ Á¦¾îÇÒ ¼ö ÀÖ´Â  ÁÜ ÄÁÆ®·ÑÀ» »ý¼ºÇÕ´Ï´Ù\r\n");
      out.write("        var zoomControl = new daum.maps.ZoomControl();\r\n");
      out.write("        map.addControl(zoomControl, daum.maps.ControlPosition.RIGHT);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        </body>\r\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
