/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2015-10-13 11:50:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.safehouse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"ko\" class=\"hfix\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>지도 샘플</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://www.openlayers.org/api/2.13/OpenLayers.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://map.vworld.kr/js/apis.do?type=Base&apiKey=9404F854-2647-364C-9CDD-107D2C8AF921\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      var map;\r\n");
      out.write("\t    var mapBounds = new OpenLayers.Bounds(123 , 32, 134 , 43);\r\n");
      out.write("\t    var mapMinZoom = 7;\r\n");
      out.write("\t    var mapMaxZoom = 19;\r\n");
      out.write("\r\n");
      out.write("        // avoid pink tiles\r\n");
      out.write("        OpenLayers.IMAGE_RELOAD_ATTEMPTS = 3;\r\n");
      out.write("        OpenLayers.Util.onImageLoadErrorColor = \"transparent\";\r\n");
      out.write("        \r\n");
      out.write("        function init(){\r\n");
      out.write("        var options = {\r\n");
      out.write("            controls: [],\r\n");
      out.write("            projection: new OpenLayers.Projection(\"EPSG:900913\"),\r\n");
      out.write("            displayProjection: new OpenLayers.Projection(\"EPSG:900913\"),\r\n");
      out.write("            units: \"m\",\r\n");
      out.write("            controls : [],\r\n");
      out.write("            numZoomLevels:21,\r\n");
      out.write("            maxResolution: 156543.0339,\r\n");
      out.write("            maxExtent: new OpenLayers.Bounds(-20037508.34, -20037508.34, 20037508.34, 20037508.34)\r\n");
      out.write("            };\r\n");
      out.write("        map = new OpenLayers.Map('basemap', options);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  \t\t\t\t\r\n");
      out.write("\t\t//======================================\r\n");
      out.write("\t\t//1. 배경지도 추가하기\r\n");
      out.write("        vBase = new vworld.Layers.Base('VBASE');\r\n");
      out.write("\t\tif (vBase != null){map.addLayer(vBase);}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("        var switcherControl = new OpenLayers.Control.LayerSwitcher();\r\n");
      out.write("        map.addControl(switcherControl);\r\n");
      out.write("        switcherControl.maximizeControl();\r\n");
      out.write("\r\n");
      out.write("        map.zoomToExtent( mapBounds.transform(map.displayProjection, map.projection ) );\r\n");
      out.write("        map.panTo(new OpenLayers.LonLat(14400821.17384,4302138.29227));\r\n");
      out.write("      //  map.panTo(14140740.892214,4521395.6921268);\r\n");
      out.write("    //  map.panTo(14140009.710048,4524707.4183749);\r\n");
      out.write("        if(\"A2SM_ODBLRCRMNLHSPOT_FEMALE\"==\"A2SM_CMMNPOI\"){\r\n");
      out.write("        \tmap.zoomTo(17);\t\r\n");
      out.write("        }else{\r\n");
      out.write("        \tmap.zoomTo(16);\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        map.addControl(new OpenLayers.Control.PanZoomBar());\r\n");
      out.write("        map.addControl(new OpenLayers.Control.MousePosition());\r\n");
      out.write("        map.addControl(new OpenLayers.Control.Navigation());\r\n");
      out.write("        //map.addControl(new OpenLayers.Control.MouseDefaults()); //2.12 No Support\r\n");
      out.write("        map.addControl(new OpenLayers.Control.Attribution({separator:\" \"}));\r\n");
      out.write("        addWmsLayer();\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\tfunction addWmsLayer(){\r\n");
      out.write("\tparam = {name:\"여성밤길 치안안전 전체\",\r\n");
      out.write(" \t\tserverUrl:\"http://www.safemap.go.kr/sm/apis.do?apikey=I2ZHCGUU-I2ZH-I2ZH-I2ZH-I2ZHCGUU3X\",\r\n");
      out.write("\t\tlayername:\"A2SM_ODBLRCRMNLHSPOT_FEMALE\",\r\n");
      out.write("\t\tstyles:\"A2SM_OdblrCrmnlHspot_Tot\"};\r\n");
      out.write("\tvar wmsLayer = new OpenLayers.Layer.WMS( param.name, param.serverUrl,\r\n");
      out.write("\t\t\t\t\t      {layers: ''+param.layername, \r\n");
      out.write("\t\t\t\t\t\t   styles:param.styles,\r\n");
      out.write("\t\t\t\t\t\t   format: 'image/png', \r\n");
      out.write("\t\t\t\t\t\t   exceptions:'text/xml',\r\n");
      out.write("\t\t\t\t\t\t   transparent: true},\r\n");
      out.write("\t\t\t\t\t      {isBaseLayer: false}\r\n");
      out.write("\t\t               );\t\r\n");
      out.write("map.addLayer(wmsLayer);\r\n");
      out.write("\r\n");
      out.write("    param = {name:\"여성사고(최근3년)\",\r\n");
      out.write("    serverUrl:\"http://www.safemap.go.kr/sm/apis.do?apikey=AGTO30NX-ERMO-FWDX-604X-G0QGERVJZH\",\r\n");
      out.write("    layername:\"A2SM_TFCACDHSPOT\",\r\n");
      out.write("    styles:\"A2SM_TfcacdHspot_Female\"};\r\n");
      out.write("    var wmsLayer = new OpenLayers.Layer.WMS( param.name, param.serverUrl,\r\n");
      out.write("    {layers: ''+param.layername,\r\n");
      out.write("    styles:param.styles,\r\n");
      out.write("    format: 'image/png',\r\n");
      out.write("    exceptions:'text/xml',\r\n");
      out.write("    transparent: true},\r\n");
      out.write("    {isBaseLayer: false}\r\n");
      out.write("    );\r\n");
      out.write("    map.addLayer(wmsLayer);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("    </script>       \r\n");
      out.write("</head>\r\n");
      out.write("  <body onload=\"init()\">\r\n");
      out.write("    <div id=\"basemap\"  style=\"width:45%;height:45%;\"></div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
